controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    methods: GET
    path: /
    controller: App\Controller\VinylController::homepage

browse:
    methods: GET
    path: /browse/{slug}
    controller: App\Controller\VinylController::browse
    defaults:
        slug:

