controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    methods: GET
    path: /
    controller: App\Controller\VinylController::homepage